spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Desktop/h2/bin/jpa
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace